### ISSUE TITLE
Can't create own models to spatia-room database (Java/Kotlin)

### ISSUE THREAD

**Issue by nskola** [anboralabs/spatia-room#9] opened 2021-10-07 12:09 UTC
I'm trying to use this library with existing Android project. It's written in Java, so the models, daos and appDataBase class are also Java classes. I managed to initialize the spatia-room database but my own database models/tables are not found in the database. Only the geospatial related default tables are created. Do you know if the problem is related to java/kotlin interaction or something else? I don't get any build time errors.

**Comment by dalgarins** [comment] 2021-10-12 01:35
@nskola I decided to modify the demo app and add dagger and hilt in my case with the library and everything is working,
<img width="907" alt="Captura de Pantalla 2021-10-11 a la(s) 8 32 09 p  m" src="https://user-images.githubusercontent.com/8527174/136876147-7589806a-7b12-41f1-9dec-cf2fafd07655.png">

the variable contract has all the contracts saved in the db.

the repo branch is: `room-hilt ` maybe you want to review.

**Comment by dalgarins** [comment] 2021-10-12 01:51
I think your issue it's related with database version in the `AppDatabase` if you had the app installed and only you updated the class without upgrade version that could be the issue. 

I'm going to close the issue because the library it's working and seems to be another problem related with your project.

**Comment by nskola** [comment] 2021-10-14 15:15
I didn't find the cause. It may have something to do with the room library version numbers or something. The problem wasn't in the database versioning, because I reinstalled the app between launches. Thank you anyway.

**Comment by nskola** [comment] 2021-10-15 06:25
Room version 2.3.0.

I ended up with different solution, but I will test the branch later.

**Comment by dalgarins** [comment] 2021-11-21 02:39
@nskola there were a break change with android room: 2.3.0, right now the issue is fixed, I have updated the README. Please read it to get more information.

**Closed** 2021-11-21 02:39 UTC
